const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

async function generateVoucher({
  voucherNo, date, agentName, agentPhone,
  guestName, guestMobile, ciDate, coDate,
  nights, rooms, roomType, plan, extraBed,
  extraBedType, rate, roomTotal, extraCharge, grandTotal
}) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 40 });
    const filePath = path.join('/tmp', `voucher-${voucherNo}.pdf`);
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    // Colors
    const GOLD = '#C9A84C';
    const DARK = '#1a1a2e';
    const GRAY = '#666666';
    const LIGHT = '#f5f5f5';

    // Header background
    doc.rect(0, 0, 595, 100).fill(DARK);

    // Hotel name
    doc.fillColor(GOLD).fontSize(22).font('Helvetica-Bold')
       .text('HOTEL SUKHSAGAR REGENCY', 40, 30, { align: 'center' });
    doc.fillColor('#ffffff').fontSize(11).font('Helvetica')
       .text('Shimla, Himachal Pradesh | +91 98160 03322', 40, 58, { align: 'center' });
    doc.fillColor('#ffffff').fontSize(10)
       .text('info@sukhsagarregency.com | www.sukhsagarregency.com', 40, 74, { align: 'center' });

    // Voucher title bar
    doc.rect(0, 100, 595, 35).fill(GOLD);
    doc.fillColor('#fff').fontSize(14).font('Helvetica-Bold')
       .text('BOOKING VOUCHER', 40, 110, { align: 'center' });

    // Voucher & date info
    doc.rect(40, 148, 240, 55).fill(LIGHT).stroke('#eee');
    doc.rect(315, 148, 240, 55).fill(LIGHT).stroke('#eee');

    doc.fillColor(GRAY).fontSize(9).font('Helvetica')
       .text('VOUCHER NO', 55, 158);
    doc.fillColor(DARK).fontSize(12).font('Helvetica-Bold')
       .text(voucherNo, 55, 170);

    doc.fillColor(GRAY).fontSize(9).font('Helvetica')
       .text('DATE', 330, 158);
    doc.fillColor(DARK).fontSize(12).font('Helvetica-Bold')
       .text(date, 330, 170);

    // Section helper
    function section(title, y) {
      doc.rect(40, y, 515, 22).fill(GOLD);
      doc.fillColor('#fff').fontSize(10).font('Helvetica-Bold')
         .text(title, 50, y + 6);
      return y + 22;
    }

    function row(label, value, y, shade) {
      if (shade) doc.rect(40, y, 515, 22).fill('#fafafa');
      doc.fillColor(GRAY).fontSize(9).font('Helvetica')
         .text(label, 50, y + 6);
      doc.fillColor(DARK).fontSize(10).font('Helvetica-Bold')
         .text(String(value), 200, y + 6);
      return y + 22;
    }

    // Agent details
    let y = section('AGENT DETAILS', 218);
    y = row('Agent Name', agentName, y, false);
    y = row('Agent Phone', agentPhone, y, true);

    // Guest details
    y = section('GUEST DETAILS', y + 8);
    y = row('Guest Name', guestName, y, false);
    y = row('Guest Mobile', guestMobile, y, true);

    // Booking details
    y = section('BOOKING DETAILS', y + 8);
    y = row('Check-in Date', ciDate, y, false);
    y = row('Check-out Date', coDate, y, true);
    y = row('No. of Nights', nights + ' Night(s)', y, false);
    y = row('Room Type', rooms + ' x ' + roomType, y, true);
    y = row('Meal Plan', plan, y, false);
    y = row('Extra Bed', extraBed ? extraBedType : 'None', y, true);

    // Amount details
    y = section('AMOUNT DETAILS', y + 8);
    y = row('Rate per Night', 'Rs.' + Math.round(rate).toLocaleString('en-IN'), y, false);
    y = row('Room Charges', 'Rs.' + Math.round(roomTotal).toLocaleString('en-IN'), y, true);
    if (extraCharge > 0) {
      y = row('Extra Bed Charges', 'Rs.' + Math.round(extraCharge).toLocaleString('en-IN'), y, false);
    }

    // Total row
    doc.rect(40, y, 515, 28).fill(GOLD);
    doc.fillColor('#fff').fontSize(11).font('Helvetica-Bold')
       .text('TOTAL AMOUNT', 50, y + 8);
    doc.fillColor('#fff').fontSize(13).font('Helvetica-Bold')
       .text('Rs.' + Math.round(grandTotal).toLocaleString('en-IN'), 200, y + 7);
    y += 28;

    // Terms
    y += 15;
    doc.rect(40, y, 515, 60).fill(LIGHT).stroke('#eee');
    doc.fillColor(GRAY).fontSize(8).font('Helvetica')
       .text('TERMS & CONDITIONS', 50, y + 8);
    doc.fillColor(GRAY).fontSize(8)
       .text('1. Check-in time: 12:00 PM | Check-out time: 11:00 AM', 50, y + 20)
       .text('2. This voucher is valid only for the dates mentioned above.', 50, y + 32)
       .text('3. Please carry a valid photo ID at the time of check-in.', 50, y + 44);

    // Footer
    doc.rect(0, 770, 595, 72).fill(DARK);
    doc.fillColor(GOLD).fontSize(10).font('Helvetica-Bold')
       .text('Hotel Sukhsagar Regency', 40, 782, { align: 'center' });
    doc.fillColor('#fff').fontSize(9).font('Helvetica')
       .text('Shimla, Himachal Pradesh | Tel: +91 98160 03322 | info@sukhsagarregency.com', 40, 798, { align: 'center' });
    doc.fillColor(GRAY).fontSize(8)
       .text('Generated by HotelEase PMS | ' + new Date().toLocaleString('en-IN'), 40, 816, { align: 'center' });

    doc.end();
    stream.on('finish', () => resolve(filePath));
    stream.on('error', reject);
  });
}

module.exports = { generateVoucher };
